# Generated by Django 2.2.3 on 2019-07-17 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='citydict',
            name='des',
            field=models.CharField(max_length=200, verbose_name='城市描述'),
        ),
        migrations.AlterField(
            model_name='citydict',
            name='name',
            field=models.CharField(max_length=50, verbose_name='城市名字'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='address',
            field=models.CharField(max_length=100, verbose_name='机构地址'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='course_num',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='des',
            field=models.TextField(verbose_name='机构描述'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(max_length=200, upload_to='org/%Y/%m', verbose_name='机构照片'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='name',
            field=models.CharField(max_length=50, verbose_name='机构名字'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学生人数'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=20, verbose_name='讲师年龄'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(max_length=200, upload_to='teacher/%Y/%m', verbose_name='讲师头像'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='讲师姓名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_company',
            field=models.CharField(max_length=50, verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=50, verbose_name='工作地点'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_year',
            field=models.IntegerField(default=0, verbose_name='工龄'),
        ),
    ]
