# Generated by Django 2.2.3 on 2019-07-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '机构'), (2, '课程'), (3, '讲师')], default=3),
        ),
    ]
